name: CI
on:
  push:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ^2
          cache: true
      - run: deno ci
      - name: Start PostgreSQL test environment
        run: docker compose up --build --wait
      - name: Test
        run: deno task ci:test
        env:
          TEST_LOGIN_DB: pg://postgres@127.0.0.1:5432/postgres
          TEST_PASSWORD_DB: pg://auth_password:password-secret@127.0.0.1:5432/auth_test
          TEST_SCRAM_DB: pg://auth_scram:scram-secret@127.0.0.1:5432/auth_test
          TEST_TLS_DB: pg://auth_tls:tls-secret@localhost:5432/auth_test
          TEST_TLS_CA: ./test/fixtures/tls/ca.crt
      - name: Stop PostgreSQL test environment
        if: always()
        run: docker compose down -v
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ^2
          cache: true
      - run: deno ci
      - name: publish dry-run
        run: deno publish --dry-run
